### ISSUE TITLE
Drylab/services statistics/services requested: repeted graphs?

### ISSUE THREAD

**Issue by jlgarciapacheco** [BU-ISCIII/iSkyLIMS-drylab#23]
when asking for statistics for a given user, there seems to be two instances of each of the following graphs in the provided information:
-service requested by center
-service requested by area

Ponder to choose one representation of each and dump the other.

**Comment by luissian** [comment]
The statistics for user does not have to display the service requested by area neither the "service request by area".
These graphs are related to "Service Request " option.  The graphs are not duplicate and each one shows the statistic information by center and by area. 
The fact that both graphic have the same value is because to the test information stored on data base and not because a bug in the code
